name: bio-embeddings
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - cudatoolkit=11.6
  - jax<0.2.0
  - jaxlib=0.1.55
  - pip:
    - jax-unirep==1.0.3
    - bio-embeddings[all]
    - kaleido
