# This config uses the original paramters from Mathias Jensen
# but with an esm1b embedding
default:
    seed: 15
    experiment_index: '07'
    model: CNN_CDR123_global_max
    data: nettcr_train_swapped_peptide_ls_3_26_peptides_full_tcr_final.csv
    patience: 100
    dropout_rate: 0.6
    encoding: blosum50_20aa
    epochs: 200
    batch_size: 64
    sample_weight: True
    embedding_model_name: esm1b
    dense_layer_units: 500
