# No dropout and no weighting
default:
    experiment_index: '04'
    seed: 15
    model: CNN_CDR123_global_max
    data: nettcr_train_swapped_peptide_ls_3_26_peptides_full_tcr_final.csv
    patience: 100
    dropout_rate: 0
    epochs: 200
    batch_size: 64
    weight_peptides: False
    embedding_name_tcr: blosum50_20aa
    embedding_name_peptide: blosum50_20aa
    padding_value_peptide: -5
    padding_side_peptide: right
    truncating_side_peptide: right
    padding_value_tcr: -5
    padding_side_tcr: right
    truncating_side_tcr: right
    peptide_selection: null
    peptide_normalization_divisor: 5
    tcr_normalization_divisor: 5
    learning_rate: 0.001
    convolution_filters_count: 16
    hidden_units_count: 64
