# ESM1b for both TCR and peptide
default:
    experiment_index: '13'
    seed: 15
    model: CNN_CDR123_global_max
    data: nettcr_train_swapped_peptide_ls_3_26_peptides_full_tcr_final.csv
    patience: 100
    dropout_rate: 0.6
    epochs: 200
    batch_size: 64
    weight_peptides: True
    embedding_name_tcr: esm1b
    embedding_name_peptide: esm1b
    padding_value_peptide: 0
    padding_side_peptide: right
    truncating_side_peptide: right
    padding_value_tcr: 0
    padding_side_tcr: right
    truncating_side_tcr: right
    peptide_selection: null
    peptide_normalization_divisor: 20
    tcr_normalization_divisor: 20
    learning_rate: 0.001
    convolution_filters_count: 16
    hidden_units_count: 64
