# ESM1b with feed forward model architecture
# With dropout
default:
    model_index: '08'
    model_architecture_name: ff_CDR123
    patience: 100
    dropout_rate: 0.6
    epochs: 2000
    batch_size: 64
    weight_peptides: True
    embedder_index_tcr: '02'
    embedder_index_peptide: '01'
    padding_value_peptide: -5
    padding_side_peptide: right
    truncating_side_peptide: right
    padding_value_tcr: 0
    padding_side_tcr: right
    truncating_side_tcr: right
    peptide_selection: null
    peptide_normalization_divisor: 5
    tcr_normalization_divisor: 20
    learning_rate: 0.001
    convolution_filters_count: null
    hidden_units_count: 64
    mixed_precision: False
