# This config uses the original paramters from Mathias Jensen
# But with a normalisation divisor of 40 for TCR
default:
    model_index: '080'
    model_architecture_name: CNN_CDR123_global_max
    patience: 100
    start_from_epoch: 200
    dropout_rate: 0.6
    epochs: 1000
    batch_size: 64
    weight_peptides: True
    embedder_index_tcr: '01'
    embedder_index_peptide: '01'
    embedder_index_cdr3: null
    padding_value_peptide: -5
    padding_side_peptide: right
    truncating_side_peptide: right
    padding_value_tcr: -5
    padding_side_tcr: right
    truncating_side_tcr: right
    peptide_selection: null
    peptide_clip_min: null
    peptide_clip_max: null
    tcr_clip_min: null
    tcr_clip_max: null
    cdr3_clip_min: null
    cdr3_clip_max: null
    peptide_normalization_divisor: 5
    tcr_normalization_divisor: 40
    cdr3_normalization_divisor: 40
    learning_rate: 0.001
    convolution_filters_count: 16
    hidden_units_count: 64
    mixed_precision: False
    pep_conv_activation: relu
    cdr_conv_activation: relu
