# ESM1b with twice the amount of convolution filters and hidden units
default:
    model_index: '06'
    seed: 15
    model_architecture_name: CNN_CDR123_global_max
    data_filename: nettcr_train_swapped_peptide_ls_3_26_peptides_full_tcr_final.csv
    patience: 100
    dropout_rate: 0.6
    epochs: 1000
    batch_size: 64
    weight_peptides: True
    embedding_name_tcr: esm1b
    embedding_name_peptide: blosum50_20aa
    padding_value_peptide: -5
    padding_side_peptide: right
    truncating_side_peptide: right
    padding_value_tcr: 0
    padding_side_tcr: right
    truncating_side_tcr: right
    peptide_selection: null
    peptide_normalization_divisor: 5
    tcr_normalization_divisor: 20
    learning_rate: 0.001
    convolution_filters_count: 32
    hidden_units_count: 128
